version: '3.8'

services:
  redis:
    image:  redis:7-alpine
    container_name: template_redis
    ports:
      - "6379:6379"
    restart:  always
  
  postgres:
    image: postgres:15-alpine
    container_name: template_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=template
    restart: always
